In [1]:
import numpy as np

In [2]:
tmpList = [1,2,3]
tmpArr = np.array(tmpList)
print(tmpArr)
print(tmpArr.shape)

[1 2 3]
(3,)


In [10]:
tmpList2 = [[1,2,3], [3,4,5], [6,7,8], [9,10,11]]
tmpArr2 = np.array(tmpList2)
print(tmpArr2)
print(tmpArr2.shape)

[[ 1  2  3]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [11]:
print(f' first row {tmpArr2[0]} , second row {tmpArr2[1]}, last row {tmpArr2[-1]} ')

 first row [1 2 3] , second row [3 4 5], last row [ 9 10 11] 


In [12]:
print(f' element in 2nd row, 3rd col {tmpArr2[1,2]} ')

 element in 2nd row, 3rd col 5 


In [13]:
secCol = tmpArr2[:,1]
print(f' 2nd column is {secCol} shape is {secCol.shape} ')

 2nd column is [ 2  4  7 10] shape is (4,) 


In [14]:
#simple arithmetic
arr1 = np.array([1,2,3]) 
arr2 = np.array([4,5,6])
sArr = arr1 + arr2
dArr = arr1 - arr2
mArr = arr1 * arr2
divArr = arr1 / arr2
print(sArr)
print(dArr)
print(mArr)
print(divArr)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
