In [1]:
import numpy as np

In [2]:
tmpList = [1,2,3]
tmpArr = np.array(tmpList)
print(tmpArr)
print(tmpArr.shape)

[1 2 3]
(3,)


In [10]:
tmpList2 = [[1,2,3], [3,4,5], [6,7,8], [9,10,11]]
tmpArr2 = np.array(tmpList2)
print(tmpArr2)
print(tmpArr2.shape)

[[ 1  2  3]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [11]:
print(f' first row {tmpArr2[0]} , second row {tmpArr2[1]}, last row {tmpArr2[-1]} ')

 first row [1 2 3] , second row [3 4 5], last row [ 9 10 11] 


In [12]:
print(f' element in 2nd row, 3rd col {tmpArr2[1,2]} ')

 element in 2nd row, 3rd col 5 


In [13]:
secCol = tmpArr2[:,1]
print(f' 2nd column is {secCol} shape is {secCol.shape} ')

 2nd column is [ 2  4  7 10] shape is (4,) 


In [14]:
#simple arithmetic
arr1 = np.array([1,2,3]) 
arr2 = np.array([4,5,6])
sArr = arr1 + arr2
dArr = arr1 - arr2
mArr = arr1 * arr2
divArr = arr1 / arr2
print(sArr)
print(dArr)
print(mArr)
print(divArr)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [16]:
nRandArr = np.random.normal(25, 5, 20)
print(nRandArr)

[20.00968866 20.80786967 24.75435915 20.23340848 33.55236348 24.44129638
 25.47788437 23.05963656 22.64768389 28.11014451 22.76610105 22.02935802
 32.24109917 20.64376708 15.6978106  19.29473582 23.18187961 26.80022063
 21.28838688 24.81686912]


In [22]:
print(f' first 3 elems {nRandArr[:3]} ')
print(f' all after 15th elems {nRandArr[15:]} ')
tmpLastTwo = nRandArr[-2:].tolist()
print(f' last 2 elem {tmpLastTwo} ')
tmpLastTwo.extend([1.2, 2.3])
print(f' after extension {tmpLastTwo} ')
tmpLastTwo.append(3.5)
print(f' after appending {tmpLastTwo} ')
tmpLastTwo.sort(reverse=True)
print(f' after sorting in reverse {tmpLastTwo} ')

 first 3 elems [20.00968866 20.80786967 24.75435915] 
 all after 15th elems [19.29473582 23.18187961 26.80022063 21.28838688 24.81686912] 
 last 2 elem [21.288386880398026, 24.816869118213084] 
 after extension [21.288386880398026, 24.816869118213084, 1.2, 2.3] 
 after appending [21.288386880398026, 24.816869118213084, 1.2, 2.3, 3.5] 
 after sorting in reverse [24.816869118213084, 21.288386880398026, 3.5, 2.3, 1.2] 
